export const NAME_FIELD = 'name'
export const ID_FIELD = 'id'
export const DEADLINE_FIELD = 'deadline'
export const IS_DONE_FIELD = 'is_done'
export const CREATED_AT_FIELD = 'created_at'
export const DONE_AT_FIELD = 'done_at'
